# Generated by Django 5.0.2 on 2024-02-27 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='celular',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000000)]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
