# Generated by Django 5.0.2 on 2024-03-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_tutor_cidade_alter_tutor_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='cidade',
            new_name='municipio',
        ),
    ]
