# Generated by Django 5.0.2 on 2024-03-10 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_rename_cidade_tutor_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='municipio',
        ),
        migrations.AddField(
            model_name='tutor',
            name='cep',
            field=models.CharField(default=14409242, max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter 8 dígitos numéricos.', regex='^\\d{8}$')]),
            preserve_default=False,
        ),
    ]
