# Generated by Django 5.0.2 on 2024-03-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_remove_tutor_estado_remove_tutor_municipio_tutor_cep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=100)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('raca', models.CharField(max_length=50)),
                ('dtVaci', models.DateField()),
                ('dtNasc', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('pedigree', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
